---
- name: download ccminer
  shell: /bin/curl -o /root/ccminer-2.2.4-1.el7.centos.x86_64.rpm http://ftp.redsleeve.org/pub/misc/mining/RPMS/ccminer-2.2.4-1.el7.centos.x86_64.rpm

- name: install ccminer
  yum:
    name: /root/ccminer-2.2.4-1.el7.centos.x86_64.rpm
    state: present
