---
- name: download ccminer
  shell: /bin/curl -o /root/ccminerx-1.5.4-1.el7.centos.x86_64.rpm http://ftp.redsleeve.org/pub/misc/mining/RPMS/ccminerx-1.5.4-1.el7.centos.x86_64.rpm

- name: install ccminer
  yum:
    name: /root/ccminerx-1.5.4-1.el7.centos.x86_64.rpm
    state: present
